// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: action.sql

package sqlcgen

import (
	"context"
	"time"
)

const getAction = `-- name: GetAction :one
SELECT id, goal_id, user_id, milestone_id, competency_id, title, detail,
    practice_format, estimated_min, minimal_variant, difficulty_hint, generated_by,
    origin_kind, status, skip_reason, resolved_at, created_at
FROM next_action WHERE id = $1 AND user_id = $2
`

type GetActionParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetAction(ctx context.Context, arg GetActionParams) (NextAction, error) {
	row := q.db.QueryRow(ctx, getAction, arg.ID, arg.UserID)
	var i NextAction
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.MilestoneID,
		&i.CompetencyID,
		&i.Title,
		&i.Detail,
		&i.PracticeFormat,
		&i.EstimatedMin,
		&i.MinimalVariant,
		&i.DifficultyHint,
		&i.GeneratedBy,
		&i.OriginKind,
		&i.Status,
		&i.SkipReason,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingAction = `-- name: GetPendingAction :one
SELECT id, goal_id, user_id, milestone_id, competency_id, title, detail,
    practice_format, estimated_min, minimal_variant, difficulty_hint, generated_by,
    origin_kind, status, skip_reason, resolved_at, created_at
FROM next_action WHERE goal_id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingAction(ctx context.Context, goalID string) (NextAction, error) {
	row := q.db.QueryRow(ctx, getPendingAction, goalID)
	var i NextAction
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.MilestoneID,
		&i.CompetencyID,
		&i.Title,
		&i.Detail,
		&i.PracticeFormat,
		&i.EstimatedMin,
		&i.MinimalVariant,
		&i.DifficultyHint,
		&i.GeneratedBy,
		&i.OriginKind,
		&i.Status,
		&i.SkipReason,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertNextAction = `-- name: InsertNextAction :exec
INSERT INTO next_action (id, goal_id, user_id, milestone_id, competency_id, title, detail,
    practice_format, estimated_min, minimal_variant, difficulty_hint, generated_by,
    origin_kind, status, skip_reason, resolved_at, created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
`

type InsertNextActionParams struct {
	ID             string
	GoalID         string
	UserID         string
	MilestoneID    *string
	CompetencyID   *string
	Title          string
	Detail         *string
	PracticeFormat *string
	EstimatedMin   int16
	MinimalVariant *string
	DifficultyHint *string
	GeneratedBy    string
	OriginKind     *string
	Status         string
	SkipReason     *string
	ResolvedAt     *time.Time
	CreatedAt      time.Time
}

func (q *Queries) InsertNextAction(ctx context.Context, arg InsertNextActionParams) error {
	_, err := q.db.Exec(ctx, insertNextAction,
		arg.ID,
		arg.GoalID,
		arg.UserID,
		arg.MilestoneID,
		arg.CompetencyID,
		arg.Title,
		arg.Detail,
		arg.PracticeFormat,
		arg.EstimatedMin,
		arg.MinimalVariant,
		arg.DifficultyHint,
		arg.GeneratedBy,
		arg.OriginKind,
		arg.Status,
		arg.SkipReason,
		arg.ResolvedAt,
		arg.CreatedAt,
	)
	return err
}

const resolveNextAction = `-- name: ResolveNextAction :exec
UPDATE next_action SET status = $2, skip_reason = $3, resolved_at = $4
WHERE id = $1
`

type ResolveNextActionParams struct {
	ID         string
	Status     string
	SkipReason *string
	ResolvedAt *time.Time
}

func (q *Queries) ResolveNextAction(ctx context.Context, arg ResolveNextActionParams) error {
	_, err := q.db.Exec(ctx, resolveNextAction,
		arg.ID,
		arg.Status,
		arg.SkipReason,
		arg.ResolvedAt,
	)
	return err
}
