// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: action.sql

package sqlcgen

import (
	"context"
	"time"
)

const getAction = `-- name: GetAction :one
SELECT id, goal_id, user_id, milestone_id, competency_id, title, detail,
    practice_format, estimated_min, minimal_variant, difficulty_hint, generated_by,
    origin_kind, status, skip_reason, resolved_at, created_at
FROM next_action WHERE id = $1 AND user_id = $2
`

type GetActionParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetAction(ctx context.Context, arg GetActionParams) (NextAction, error) {
	row := q.db.QueryRow(ctx, getAction, arg.ID, arg.UserID)
	var i NextAction
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.MilestoneID,
		&i.CompetencyID,
		&i.Title,
		&i.Detail,
		&i.PracticeFormat,
		&i.EstimatedMin,
		&i.MinimalVariant,
		&i.DifficultyHint,
		&i.GeneratedBy,
		&i.OriginKind,
		&i.Status,
		&i.SkipReason,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingAction = `-- name: GetPendingAction :one
SELECT id, goal_id, user_id, milestone_id, competency_id, title, detail,
    practice_format, estimated_min, minimal_variant, difficulty_hint, generated_by,
    origin_kind, status, skip_reason, resolved_at, created_at
FROM next_action WHERE goal_id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingAction(ctx context.Context, goalID string) (NextAction, error) {
	row := q.db.QueryRow(ctx, getPendingAction, goalID)
	var i NextAction
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.MilestoneID,
		&i.CompetencyID,
		&i.Title,
		&i.Detail,
		&i.PracticeFormat,
		&i.EstimatedMin,
		&i.MinimalVariant,
		&i.DifficultyHint,
		&i.GeneratedBy,
		&i.OriginKind,
		&i.Status,
		&i.SkipReason,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertNextAction = `-- name: InsertNextAction :exec
INSERT INTO next_action (id, goal_id, user_id, milestone_id, competency_id, title, detail,
    practice_format, estimated_min, minimal_variant, difficulty_hint, generated_by,
    origin_kind, status, skip_reason, resolved_at, created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
`

type InsertNextActionParams struct {
	ID             string
	GoalID         string
	UserID         string
	MilestoneID    *string
	CompetencyID   *string
	Title          string
	Detail         *string
	PracticeFormat *string
	EstimatedMin   int16
	MinimalVariant *string
	DifficultyHint *string
	GeneratedBy    string
	OriginKind     *string
	Status         string
	SkipReason     *string
	ResolvedAt     *time.Time
	CreatedAt      time.Time
}

func (q *Queries) InsertNextAction(ctx context.Context, arg InsertNextActionParams) error {
	_, err := q.db.Exec(ctx, insertNextAction,
		arg.ID,
		arg.GoalID,
		arg.UserID,
		arg.MilestoneID,
		arg.CompetencyID,
		arg.Title,
		arg.Detail,
		arg.PracticeFormat,
		arg.EstimatedMin,
		arg.MinimalVariant,
		arg.DifficultyHint,
		arg.GeneratedBy,
		arg.OriginKind,
		arg.Status,
		arg.SkipReason,
		arg.ResolvedAt,
		arg.CreatedAt,
	)
	return err
}

const listRecentActionsByGoal = `-- name: ListRecentActionsByGoal :many
SELECT title, status, skip_reason FROM next_action
WHERE goal_id = $1 AND status != 'pending'
ORDER BY resolved_at DESC LIMIT $2
`

type ListRecentActionsByGoalParams struct {
	GoalID string
	Limit  int32
}

type ListRecentActionsByGoalRow struct {
	Title      string
	Status     string
	SkipReason *string
}

// Alimenta RecentActions/RecentTitles do prompt de A2 — só ações já
// resolvidas (pending nunca entra aqui, é sempre a que está sendo gerada).
func (q *Queries) ListRecentActionsByGoal(ctx context.Context, arg ListRecentActionsByGoalParams) ([]ListRecentActionsByGoalRow, error) {
	rows, err := q.db.Query(ctx, listRecentActionsByGoal, arg.GoalID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentActionsByGoalRow
	for rows.Next() {
		var i ListRecentActionsByGoalRow
		if err := rows.Scan(&i.Title, &i.Status, &i.SkipReason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveNextAction = `-- name: ResolveNextAction :exec
UPDATE next_action SET status = $2, skip_reason = $3, resolved_at = $4
WHERE id = $1
`

type ResolveNextActionParams struct {
	ID         string
	Status     string
	SkipReason *string
	ResolvedAt *time.Time
}

func (q *Queries) ResolveNextAction(ctx context.Context, arg ResolveNextActionParams) error {
	_, err := q.db.Exec(ctx, resolveNextAction,
		arg.ID,
		arg.Status,
		arg.SkipReason,
		arg.ResolvedAt,
	)
	return err
}

const updatePendingActionContent = `-- name: UpdatePendingActionContent :execrows
UPDATE next_action SET
    title = $2, detail = $3, practice_format = $4, estimated_min = $5,
    minimal_variant = $6, milestone_id = $7, competency_id = $8, generated_by = $9
WHERE id = $1 AND status = 'pending'
`

type UpdatePendingActionContentParams struct {
	ID             string
	Title          string
	Detail         *string
	PracticeFormat *string
	EstimatedMin   int16
	MinimalVariant *string
	MilestoneID    *string
	CompetencyID   *string
	GeneratedBy    string
}

// "Upgrade no lugar" do fallback determinístico pro resultado do A2
// (04-agentes.md §5): mesmo ID, mesmo created_at, só o conteúdo muda.
// :execrows deixa o chamador saber se a ação ainda estava pending — se não
// estava (já foi concluída/pulada enquanto o job rodava), 0 linhas afetadas
// e o resultado do agente é descartado, sem sobrescrever o que a pessoa já
// fez (03-api.md, RN-03).
func (q *Queries) UpdatePendingActionContent(ctx context.Context, arg UpdatePendingActionContentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePendingActionContent,
		arg.ID,
		arg.Title,
		arg.Detail,
		arg.PracticeFormat,
		arg.EstimatedMin,
		arg.MinimalVariant,
		arg.MilestoneID,
		arg.CompetencyID,
		arg.GeneratedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
