// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: competency.sql

package sqlcgen

import (
	"context"
	"time"
)

const countCompetenciesByGoal = `-- name: CountCompetenciesByGoal :one
SELECT count(*) FROM competency WHERE goal_id = $1 AND retired_at IS NULL
`

func (q *Queries) CountCompetenciesByGoal(ctx context.Context, goalID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCompetenciesByGoal, goalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCompetency = `-- name: GetCompetency :one
SELECT id, goal_id, user_id, pack_key, label, weight,
    current_level, confidence, baseline_level, last_evidence_at, retired_at, created_at
FROM competency WHERE id = $1 AND user_id = $2
`

type GetCompetencyParams struct {
	ID     string
	UserID string
}

type GetCompetencyRow struct {
	ID             string
	GoalID         string
	UserID         string
	PackKey        string
	Label          string
	Weight         float64
	CurrentLevel   *int16
	Confidence     string
	BaselineLevel  *int16
	LastEvidenceAt *time.Time
	RetiredAt      *time.Time
	CreatedAt      time.Time
}

func (q *Queries) GetCompetency(ctx context.Context, arg GetCompetencyParams) (GetCompetencyRow, error) {
	row := q.db.QueryRow(ctx, getCompetency, arg.ID, arg.UserID)
	var i GetCompetencyRow
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.PackKey,
		&i.Label,
		&i.Weight,
		&i.CurrentLevel,
		&i.Confidence,
		&i.BaselineLevel,
		&i.LastEvidenceAt,
		&i.RetiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCompetency = `-- name: InsertCompetency :exec
INSERT INTO competency (id, goal_id, user_id, pack_key, label, weight,
    current_level, confidence, baseline_level, last_evidence_at, retired_at, created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type InsertCompetencyParams struct {
	ID             string
	GoalID         string
	UserID         string
	PackKey        string
	Label          string
	Weight         float64
	CurrentLevel   *int16
	Confidence     string
	BaselineLevel  *int16
	LastEvidenceAt *time.Time
	RetiredAt      *time.Time
	CreatedAt      time.Time
}

func (q *Queries) InsertCompetency(ctx context.Context, arg InsertCompetencyParams) error {
	_, err := q.db.Exec(ctx, insertCompetency,
		arg.ID,
		arg.GoalID,
		arg.UserID,
		arg.PackKey,
		arg.Label,
		arg.Weight,
		arg.CurrentLevel,
		arg.Confidence,
		arg.BaselineLevel,
		arg.LastEvidenceAt,
		arg.RetiredAt,
		arg.CreatedAt,
	)
	return err
}

const insertLevelEvent = `-- name: InsertLevelEvent :exec
INSERT INTO competency_level_event
    (id, competency_id, user_id, from_level, to_level, confidence, source, assessment_id, rationale, occurred_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type InsertLevelEventParams struct {
	ID           string
	CompetencyID string
	UserID       string
	FromLevel    *int16
	ToLevel      int16
	Confidence   string
	Source       string
	AssessmentID *string
	Rationale    string
	OccurredAt   time.Time
}

func (q *Queries) InsertLevelEvent(ctx context.Context, arg InsertLevelEventParams) error {
	_, err := q.db.Exec(ctx, insertLevelEvent,
		arg.ID,
		arg.CompetencyID,
		arg.UserID,
		arg.FromLevel,
		arg.ToLevel,
		arg.Confidence,
		arg.Source,
		arg.AssessmentID,
		arg.Rationale,
		arg.OccurredAt,
	)
	return err
}

const listCompetenciesByGoal = `-- name: ListCompetenciesByGoal :many
SELECT id, goal_id, user_id, pack_key, label, weight,
    current_level, confidence, baseline_level, last_evidence_at, retired_at, created_at
FROM competency WHERE goal_id = $1 ORDER BY weight DESC, pack_key
`

type ListCompetenciesByGoalRow struct {
	ID             string
	GoalID         string
	UserID         string
	PackKey        string
	Label          string
	Weight         float64
	CurrentLevel   *int16
	Confidence     string
	BaselineLevel  *int16
	LastEvidenceAt *time.Time
	RetiredAt      *time.Time
	CreatedAt      time.Time
}

func (q *Queries) ListCompetenciesByGoal(ctx context.Context, goalID string) ([]ListCompetenciesByGoalRow, error) {
	rows, err := q.db.Query(ctx, listCompetenciesByGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetenciesByGoalRow
	for rows.Next() {
		var i ListCompetenciesByGoalRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.PackKey,
			&i.Label,
			&i.Weight,
			&i.CurrentLevel,
			&i.Confidence,
			&i.BaselineLevel,
			&i.LastEvidenceAt,
			&i.RetiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLevelEvents = `-- name: ListLevelEvents :many
SELECT id, competency_id, user_id, from_level, to_level, confidence, source, assessment_id, rationale, occurred_at
FROM competency_level_event WHERE competency_id = $1 ORDER BY occurred_at
`

func (q *Queries) ListLevelEvents(ctx context.Context, competencyID string) ([]CompetencyLevelEvent, error) {
	rows, err := q.db.Query(ctx, listLevelEvents, competencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetencyLevelEvent
	for rows.Next() {
		var i CompetencyLevelEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompetencyID,
			&i.UserID,
			&i.FromLevel,
			&i.ToLevel,
			&i.Confidence,
			&i.Source,
			&i.AssessmentID,
			&i.Rationale,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLevelEventsForGoal = `-- name: ListLevelEventsForGoal :many
SELECT e.id, e.competency_id, e.user_id, e.from_level, e.to_level, e.confidence, e.source, e.assessment_id, e.rationale, e.occurred_at
FROM competency_level_event e
JOIN competency c ON c.id = e.competency_id
WHERE c.goal_id = $1
ORDER BY e.occurred_at
`

func (q *Queries) ListLevelEventsForGoal(ctx context.Context, goalID string) ([]CompetencyLevelEvent, error) {
	rows, err := q.db.Query(ctx, listLevelEventsForGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetencyLevelEvent
	for rows.Next() {
		var i CompetencyLevelEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompetencyID,
			&i.UserID,
			&i.FromLevel,
			&i.ToLevel,
			&i.Confidence,
			&i.Source,
			&i.AssessmentID,
			&i.Rationale,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompetencyState = `-- name: UpdateCompetencyState :exec
UPDATE competency SET current_level = $2, confidence = $3, baseline_level = $4, last_evidence_at = $5
WHERE id = $1
`

type UpdateCompetencyStateParams struct {
	ID             string
	CurrentLevel   *int16
	Confidence     string
	BaselineLevel  *int16
	LastEvidenceAt *time.Time
}

func (q *Queries) UpdateCompetencyState(ctx context.Context, arg UpdateCompetencyStateParams) error {
	_, err := q.db.Exec(ctx, updateCompetencyState,
		arg.ID,
		arg.CurrentLevel,
		arg.Confidence,
		arg.BaselineLevel,
		arg.LastEvidenceAt,
	)
	return err
}
