// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package sqlcgen

import (
	"context"
	"time"
)

const countEvidenceByGoal = `-- name: CountEvidenceByGoal :one
SELECT count(*) FROM evidence WHERE goal_id = $1
`

func (q *Queries) CountEvidenceByGoal(ctx context.Context, goalID string) (int64, error) {
	row := q.db.QueryRow(ctx, countEvidenceByGoal, goalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEvidence = `-- name: GetEvidence :one
SELECT id, goal_id, user_id, action_id, kind, title, body, blob_key,
    external_url, language, supersedes_id, local_on, created_at
FROM evidence WHERE id = $1 AND user_id = $2
`

type GetEvidenceParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetEvidence(ctx context.Context, arg GetEvidenceParams) (Evidence, error) {
	row := q.db.QueryRow(ctx, getEvidence, arg.ID, arg.UserID)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.ActionID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.BlobKey,
		&i.ExternalUrl,
		&i.Language,
		&i.SupersedesID,
		&i.LocalOn,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvidence = `-- name: InsertEvidence :exec
INSERT INTO evidence (id, goal_id, user_id, action_id, kind, title, body, blob_key,
    external_url, language, supersedes_id, local_on, created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type InsertEvidenceParams struct {
	ID           string
	GoalID       string
	UserID       string
	ActionID     *string
	Kind         string
	Title        *string
	Body         *string
	BlobKey      *string
	ExternalUrl  *string
	Language     *string
	SupersedesID *string
	LocalOn      time.Time
	CreatedAt    time.Time
}

func (q *Queries) InsertEvidence(ctx context.Context, arg InsertEvidenceParams) error {
	_, err := q.db.Exec(ctx, insertEvidence,
		arg.ID,
		arg.GoalID,
		arg.UserID,
		arg.ActionID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.BlobKey,
		arg.ExternalUrl,
		arg.Language,
		arg.SupersedesID,
		arg.LocalOn,
		arg.CreatedAt,
	)
	return err
}

const insertEvidenceCompetency = `-- name: InsertEvidenceCompetency :exec
INSERT INTO evidence_competency (evidence_id, competency_id) VALUES ($1, $2)
`

type InsertEvidenceCompetencyParams struct {
	EvidenceID   string
	CompetencyID string
}

func (q *Queries) InsertEvidenceCompetency(ctx context.Context, arg InsertEvidenceCompetencyParams) error {
	_, err := q.db.Exec(ctx, insertEvidenceCompetency, arg.EvidenceID, arg.CompetencyID)
	return err
}

const listCompetencyIDsForEvidences = `-- name: ListCompetencyIDsForEvidences :many
SELECT evidence_id, competency_id FROM evidence_competency
WHERE evidence_id = ANY($1::uuid[])
`

// traz os pares (evidence_id, competency_id) pras evidências pedidas de uma
// vez só — evita N+1 ao montar o museu (§7.4).
func (q *Queries) ListCompetencyIDsForEvidences(ctx context.Context, evidenceIds []string) ([]EvidenceCompetency, error) {
	rows, err := q.db.Query(ctx, listCompetencyIDsForEvidences, evidenceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceCompetency
	for rows.Next() {
		var i EvidenceCompetency
		if err := rows.Scan(&i.EvidenceID, &i.CompetencyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceByGoalAndCompetencyAsc = `-- name: ListEvidenceByGoalAndCompetencyAsc :many
SELECT e.id, e.goal_id, e.user_id, e.action_id, e.kind, e.title, e.body, e.blob_key,
    e.external_url, e.language, e.supersedes_id, e.local_on, e.created_at
FROM evidence e
JOIN evidence_competency ec ON ec.evidence_id = e.id
WHERE e.goal_id = $1 AND ec.competency_id = $2
ORDER BY e.created_at ASC LIMIT $3
`

type ListEvidenceByGoalAndCompetencyAscParams struct {
	GoalID       string
	CompetencyID string
	Limit        int32
}

func (q *Queries) ListEvidenceByGoalAndCompetencyAsc(ctx context.Context, arg ListEvidenceByGoalAndCompetencyAscParams) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidenceByGoalAndCompetencyAsc, arg.GoalID, arg.CompetencyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evidence
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.ActionID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.BlobKey,
			&i.ExternalUrl,
			&i.Language,
			&i.SupersedesID,
			&i.LocalOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceByGoalAndCompetencyDesc = `-- name: ListEvidenceByGoalAndCompetencyDesc :many
SELECT e.id, e.goal_id, e.user_id, e.action_id, e.kind, e.title, e.body, e.blob_key,
    e.external_url, e.language, e.supersedes_id, e.local_on, e.created_at
FROM evidence e
JOIN evidence_competency ec ON ec.evidence_id = e.id
WHERE e.goal_id = $1 AND ec.competency_id = $2
ORDER BY e.created_at DESC LIMIT $3
`

type ListEvidenceByGoalAndCompetencyDescParams struct {
	GoalID       string
	CompetencyID string
	Limit        int32
}

func (q *Queries) ListEvidenceByGoalAndCompetencyDesc(ctx context.Context, arg ListEvidenceByGoalAndCompetencyDescParams) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidenceByGoalAndCompetencyDesc, arg.GoalID, arg.CompetencyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evidence
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.ActionID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.BlobKey,
			&i.ExternalUrl,
			&i.Language,
			&i.SupersedesID,
			&i.LocalOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceByGoalAsc = `-- name: ListEvidenceByGoalAsc :many
SELECT id, goal_id, user_id, action_id, kind, title, body, blob_key,
    external_url, language, supersedes_id, local_on, created_at
FROM evidence WHERE goal_id = $1 ORDER BY created_at ASC LIMIT $2
`

type ListEvidenceByGoalAscParams struct {
	GoalID string
	Limit  int32
}

func (q *Queries) ListEvidenceByGoalAsc(ctx context.Context, arg ListEvidenceByGoalAscParams) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidenceByGoalAsc, arg.GoalID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evidence
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.ActionID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.BlobKey,
			&i.ExternalUrl,
			&i.Language,
			&i.SupersedesID,
			&i.LocalOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceByGoalDesc = `-- name: ListEvidenceByGoalDesc :many
SELECT id, goal_id, user_id, action_id, kind, title, body, blob_key,
    external_url, language, supersedes_id, local_on, created_at
FROM evidence WHERE goal_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListEvidenceByGoalDescParams struct {
	GoalID string
	Limit  int32
}

func (q *Queries) ListEvidenceByGoalDesc(ctx context.Context, arg ListEvidenceByGoalDescParams) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidenceByGoalDesc, arg.GoalID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evidence
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.ActionID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.BlobKey,
			&i.ExternalUrl,
			&i.Language,
			&i.SupersedesID,
			&i.LocalOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
