// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goal.sql

package sqlcgen

import (
	"context"
	"time"
)

const countActiveGoals = `-- name: CountActiveGoals :one
SELECT count(*) FROM goal
WHERE user_id = $1 AND status IN ('active','at_risk','stagnant')
`

func (q *Queries) CountActiveGoals(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveGoals, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGoal = `-- name: GetGoal :one
SELECT id, user_id, title, archetype, pack_id, why, definition_of_done, horizon_on,
    status, scope_mode, paused_until, activated_at, last_activity_at, closed_at, created_at, updated_at
FROM goal WHERE id = $1 AND user_id = $2
`

type GetGoalParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetGoal(ctx context.Context, arg GetGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoal, arg.ID, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Archetype,
		&i.PackID,
		&i.Why,
		&i.DefinitionOfDone,
		&i.HorizonOn,
		&i.Status,
		&i.ScopeMode,
		&i.PausedUntil,
		&i.ActivatedAt,
		&i.LastActivityAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGoal = `-- name: InsertGoal :exec
INSERT INTO goal (id, user_id, title, archetype, pack_id, why, definition_of_done, horizon_on,
    status, scope_mode, paused_until, activated_at, last_activity_at, closed_at, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
`

type InsertGoalParams struct {
	ID               string
	UserID           string
	Title            string
	Archetype        string
	PackID           string
	Why              *string
	DefinitionOfDone *string
	HorizonOn        *time.Time
	Status           string
	ScopeMode        string
	PausedUntil      *time.Time
	ActivatedAt      *time.Time
	LastActivityAt   *time.Time
	ClosedAt         *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) InsertGoal(ctx context.Context, arg InsertGoalParams) error {
	_, err := q.db.Exec(ctx, insertGoal,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Archetype,
		arg.PackID,
		arg.Why,
		arg.DefinitionOfDone,
		arg.HorizonOn,
		arg.Status,
		arg.ScopeMode,
		arg.PausedUntil,
		arg.ActivatedAt,
		arg.LastActivityAt,
		arg.ClosedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listGoals = `-- name: ListGoals :many
SELECT id, user_id, title, archetype, pack_id, why, definition_of_done, horizon_on,
    status, scope_mode, paused_until, activated_at, last_activity_at, closed_at, created_at, updated_at
FROM goal WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGoals(ctx context.Context, userID string) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Archetype,
			&i.PackID,
			&i.Why,
			&i.DefinitionOfDone,
			&i.HorizonOn,
			&i.Status,
			&i.ScopeMode,
			&i.PausedUntil,
			&i.ActivatedAt,
			&i.LastActivityAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByStatus = `-- name: ListGoalsByStatus :many
SELECT id, user_id, title, archetype, pack_id, why, definition_of_done, horizon_on,
    status, scope_mode, paused_until, activated_at, last_activity_at, closed_at, created_at, updated_at
FROM goal WHERE user_id = $1 AND status = ANY($2::text[]) ORDER BY created_at DESC
`

type ListGoalsByStatusParams struct {
	UserID  string
	Column2 []string
}

func (q *Queries) ListGoalsByStatus(ctx context.Context, arg ListGoalsByStatusParams) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoalsByStatus, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Archetype,
			&i.PackID,
			&i.Why,
			&i.DefinitionOfDone,
			&i.HorizonOn,
			&i.Status,
			&i.ScopeMode,
			&i.PausedUntil,
			&i.ActivatedAt,
			&i.LastActivityAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
SELECT id FROM app_user WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const updateGoal = `-- name: UpdateGoal :execrows
UPDATE goal SET
    title = $2, why = $3, definition_of_done = $4, horizon_on = $5,
    status = $6, scope_mode = $7, paused_until = $8,
    activated_at = $9, last_activity_at = $10, closed_at = $11, updated_at = $12
WHERE id = $1
`

type UpdateGoalParams struct {
	ID               string
	Title            string
	Why              *string
	DefinitionOfDone *string
	HorizonOn        *time.Time
	Status           string
	ScopeMode        string
	PausedUntil      *time.Time
	ActivatedAt      *time.Time
	LastActivityAt   *time.Time
	ClosedAt         *time.Time
	UpdatedAt        time.Time
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGoal,
		arg.ID,
		arg.Title,
		arg.Why,
		arg.DefinitionOfDone,
		arg.HorizonOn,
		arg.Status,
		arg.ScopeMode,
		arg.PausedUntil,
		arg.ActivatedAt,
		arg.LastActivityAt,
		arg.ClosedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
