// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AgentBudget struct {
	UserID   string
	PeriodOn time.Time
	LimitUsd float64
	SpentUsd float64
}

type AgentCall struct {
	ID            string
	UserID        string
	Task          string
	Tier          string
	Model         string
	PromptVersion string
	InputTokens   *int32
	OutputTokens  *int32
	CostUsd       *float64
	LatencyMs     *int32
	Status        string
	Error         *string
	CacheHit      bool
	InputHash     *string
	Output        []byte
	CreatedAt     time.Time
}

type AppUser struct {
	ID           string
	Email        string
	PasswordHash string
	Timezone     string
	QuietHours   pgtype.Range[pgtype.Int4]
	CreatedAt    time.Time
}

type Competency struct {
	ID             string
	GoalID         string
	UserID         string
	PackKey        string
	Label          string
	Weight         float64
	CurrentLevel   *int16
	Confidence     string
	BaselineLevel  *int16
	LastEvidenceAt *time.Time
	RetiredAt      *time.Time
	RetiredReason  *string
	MergedIntoID   *string
	CreatedAt      time.Time
}

type CompetencyLevelEvent struct {
	ID           string
	CompetencyID string
	UserID       string
	FromLevel    *int16
	ToLevel      int16
	Confidence   string
	Source       string
	AssessmentID *string
	Rationale    string
	OccurredAt   time.Time
	EvidenceID   *string
}

type Device struct {
	ID         string
	UserID     string
	ExpoToken  string
	Platform   string
	LastSeenAt time.Time
	DisabledAt *time.Time
}

type Evidence struct {
	ID           string
	GoalID       string
	UserID       string
	ActionID     *string
	Kind         string
	Title        *string
	Body         *string
	BlobKey      *string
	ExternalUrl  *string
	Language     *string
	SupersedesID *string
	LocalOn      time.Time
	CreatedAt    time.Time
}

type EvidenceCompetency struct {
	EvidenceID   string
	CompetencyID string
}

type EvidenceEvalCase struct {
	EvidenceID string
	Note       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type EvidenceEvalCaseScore struct {
	EvidenceID   string
	CompetencyID string
	Level        int32
}

type Goal struct {
	ID               string
	UserID           string
	Title            string
	Archetype        string
	PackID           string
	Why              *string
	DefinitionOfDone *string
	HorizonOn        *time.Time
	Status           string
	ScopeMode        string
	PausedUntil      *time.Time
	ActivatedAt      *time.Time
	LastActivityAt   *time.Time
	ClosedAt         *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Job struct {
	ID          int64
	Kind        string
	Payload     []byte
	UniqueKey   *string
	RunAt       time.Time
	Attempts    int16
	MaxAttempts int16
	LockedAt    *time.Time
	LockedBy    *string
	Status      string
	LastError   *string
	CreatedAt   time.Time
}

type Milestone struct {
	ID                 string
	TrackID            string
	GoalID             string
	UserID             string
	Ordinal            int32
	Title              string
	CompletionCriteria string
	Status             string
	CompletedAt        *time.Time
}

type MilestoneCompetency struct {
	MilestoneID  string
	CompetencyID string
}

type NextAction struct {
	ID             string
	GoalID         string
	UserID         string
	MilestoneID    *string
	CompetencyID   *string
	Title          string
	Detail         *string
	PracticeFormat *string
	EstimatedMin   int16
	MinimalVariant *string
	DifficultyHint *string
	GeneratedBy    string
	OriginKind     *string
	Status         string
	SkipReason     *string
	ResolvedAt     *time.Time
	CreatedAt      time.Time
}

type Outbox struct {
	ID          int64
	Aggregate   string
	AggregateID string
	EventType   string
	Payload     []byte
	OccurredAt  time.Time
	PublishedAt *time.Time
}

type Probe struct {
	ID         string
	GoalID     string
	UserID     string
	Status     string
	AskedCount int16
	CreatedAt  time.Time
	ClosedAt   *time.Time
}

type ProbeTurn struct {
	ID            string
	ProbeID       string
	CompetencyID  *string
	Ordinal       int16
	Question      string
	Answer        *string
	InferredLevel *int16
	AnsweredAt    *time.Time
}

type ProcessedEvent struct {
	Consumer    string
	EventID     int64
	ProcessedAt time.Time
}

type Proposal struct {
	ID           string
	UserID       string
	GoalID       *string
	Kind         string
	Payload      []byte
	Rationale    string
	AgentCallID  *string
	Status       string
	ResolvedAt   *time.Time
	RejectReason *string
	ExpiresAt    *time.Time
	CreatedAt    time.Time
}

type Session struct {
	ID          string
	GoalID      string
	UserID      string
	ActionID    *string
	StartedAt   time.Time
	DurationMin int16
	Note        *string
	Energy      *int16
	LocalOn     time.Time
	CreatedAt   time.Time
}

type Track struct {
	ID           string
	GoalID       string
	UserID       string
	Version      int32
	GeneratedBy  string
	AcceptedAt   *time.Time
	SupersededAt *time.Time
	CreatedAt    time.Time
}

type UserSession struct {
	ID        string
	UserID    string
	TokenHash string
	Kind      string
	UserAgent *string
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}
