// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probe.sql

package sqlcgen

import (
	"context"
	"time"
)

const getProbeByGoal = `-- name: GetProbeByGoal :one
SELECT id, goal_id, user_id, status, asked_count, closed_at
FROM probe WHERE goal_id = $1
`

type GetProbeByGoalRow struct {
	ID         string
	GoalID     string
	UserID     string
	Status     string
	AskedCount int16
	ClosedAt   *time.Time
}

func (q *Queries) GetProbeByGoal(ctx context.Context, goalID string) (GetProbeByGoalRow, error) {
	row := q.db.QueryRow(ctx, getProbeByGoal, goalID)
	var i GetProbeByGoalRow
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.Status,
		&i.AskedCount,
		&i.ClosedAt,
	)
	return i, err
}

const insertProbe = `-- name: InsertProbe :exec
INSERT INTO probe (id, goal_id, user_id, status, asked_count, closed_at)
VALUES ($1,$2,$3,$4,$5,$6)
`

type InsertProbeParams struct {
	ID         string
	GoalID     string
	UserID     string
	Status     string
	AskedCount int16
	ClosedAt   *time.Time
}

func (q *Queries) InsertProbe(ctx context.Context, arg InsertProbeParams) error {
	_, err := q.db.Exec(ctx, insertProbe,
		arg.ID,
		arg.GoalID,
		arg.UserID,
		arg.Status,
		arg.AskedCount,
		arg.ClosedAt,
	)
	return err
}

const insertProbeTurn = `-- name: InsertProbeTurn :exec
INSERT INTO probe_turn (id, probe_id, competency_id, ordinal, question, answer, inferred_level, answered_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertProbeTurnParams struct {
	ID            string
	ProbeID       string
	CompetencyID  *string
	Ordinal       int16
	Question      string
	Answer        *string
	InferredLevel *int16
	AnsweredAt    *time.Time
}

func (q *Queries) InsertProbeTurn(ctx context.Context, arg InsertProbeTurnParams) error {
	_, err := q.db.Exec(ctx, insertProbeTurn,
		arg.ID,
		arg.ProbeID,
		arg.CompetencyID,
		arg.Ordinal,
		arg.Question,
		arg.Answer,
		arg.InferredLevel,
		arg.AnsweredAt,
	)
	return err
}

const listProbeTurnsByProbe = `-- name: ListProbeTurnsByProbe :many
SELECT id, probe_id, competency_id, ordinal, question, answer, inferred_level, answered_at
FROM probe_turn WHERE probe_id = $1 ORDER BY ordinal
`

func (q *Queries) ListProbeTurnsByProbe(ctx context.Context, probeID string) ([]ProbeTurn, error) {
	rows, err := q.db.Query(ctx, listProbeTurnsByProbe, probeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProbeTurn
	for rows.Next() {
		var i ProbeTurn
		if err := rows.Scan(
			&i.ID,
			&i.ProbeID,
			&i.CompetencyID,
			&i.Ordinal,
			&i.Question,
			&i.Answer,
			&i.InferredLevel,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProbe = `-- name: UpdateProbe :exec
UPDATE probe SET status = $2, asked_count = $3, closed_at = $4 WHERE id = $1
`

type UpdateProbeParams struct {
	ID         string
	Status     string
	AskedCount int16
	ClosedAt   *time.Time
}

func (q *Queries) UpdateProbe(ctx context.Context, arg UpdateProbeParams) error {
	_, err := q.db.Exec(ctx, updateProbe,
		arg.ID,
		arg.Status,
		arg.AskedCount,
		arg.ClosedAt,
	)
	return err
}

const updateProbeTurnAnswer = `-- name: UpdateProbeTurnAnswer :exec
UPDATE probe_turn SET answer = $2, answered_at = $3 WHERE id = $1
`

type UpdateProbeTurnAnswerParams struct {
	ID         string
	Answer     *string
	AnsweredAt *time.Time
}

func (q *Queries) UpdateProbeTurnAnswer(ctx context.Context, arg UpdateProbeTurnAnswerParams) error {
	_, err := q.db.Exec(ctx, updateProbeTurnAnswer, arg.ID, arg.Answer, arg.AnsweredAt)
	return err
}
