// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proposal.sql

package sqlcgen

import (
	"context"
	"time"
)

const getProposal = `-- name: GetProposal :one
SELECT id, user_id, goal_id, kind, payload, rationale, agent_call_id, status,
    resolved_at, reject_reason, expires_at, created_at
FROM proposal WHERE id = $1 AND user_id = $2
`

type GetProposalParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetProposal(ctx context.Context, arg GetProposalParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, getProposal, arg.ID, arg.UserID)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalID,
		&i.Kind,
		&i.Payload,
		&i.Rationale,
		&i.AgentCallID,
		&i.Status,
		&i.ResolvedAt,
		&i.RejectReason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertProposal = `-- name: InsertProposal :exec
INSERT INTO proposal (id, user_id, goal_id, kind, payload, rationale, agent_call_id, status, expires_at, created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type InsertProposalParams struct {
	ID          string
	UserID      string
	GoalID      *string
	Kind        string
	Payload     []byte
	Rationale   string
	AgentCallID *string
	Status      string
	ExpiresAt   *time.Time
	CreatedAt   time.Time
}

func (q *Queries) InsertProposal(ctx context.Context, arg InsertProposalParams) error {
	_, err := q.db.Exec(ctx, insertProposal,
		arg.ID,
		arg.UserID,
		arg.GoalID,
		arg.Kind,
		arg.Payload,
		arg.Rationale,
		arg.AgentCallID,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const listProposalsByUserAndStatus = `-- name: ListProposalsByUserAndStatus :many
SELECT id, user_id, goal_id, kind, payload, rationale, agent_call_id, status,
    resolved_at, reject_reason, expires_at, created_at
FROM proposal WHERE user_id = $1 AND status = $2 ORDER BY created_at DESC
`

type ListProposalsByUserAndStatusParams struct {
	UserID string
	Status string
}

func (q *Queries) ListProposalsByUserAndStatus(ctx context.Context, arg ListProposalsByUserAndStatusParams) ([]Proposal, error) {
	rows, err := q.db.Query(ctx, listProposalsByUserAndStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proposal
	for rows.Next() {
		var i Proposal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoalID,
			&i.Kind,
			&i.Payload,
			&i.Rationale,
			&i.AgentCallID,
			&i.Status,
			&i.ResolvedAt,
			&i.RejectReason,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposalsByUserStatusAndGoal = `-- name: ListProposalsByUserStatusAndGoal :many
SELECT id, user_id, goal_id, kind, payload, rationale, agent_call_id, status,
    resolved_at, reject_reason, expires_at, created_at
FROM proposal WHERE user_id = $1 AND status = $2 AND goal_id = $3 ORDER BY created_at DESC
`

type ListProposalsByUserStatusAndGoalParams struct {
	UserID string
	Status string
	GoalID *string
}

func (q *Queries) ListProposalsByUserStatusAndGoal(ctx context.Context, arg ListProposalsByUserStatusAndGoalParams) ([]Proposal, error) {
	rows, err := q.db.Query(ctx, listProposalsByUserStatusAndGoal, arg.UserID, arg.Status, arg.GoalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proposal
	for rows.Next() {
		var i Proposal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoalID,
			&i.Kind,
			&i.Payload,
			&i.Rationale,
			&i.AgentCallID,
			&i.Status,
			&i.ResolvedAt,
			&i.RejectReason,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveProposal = `-- name: ResolveProposal :exec
UPDATE proposal SET status = $2, resolved_at = $3, reject_reason = $4 WHERE id = $1
`

type ResolveProposalParams struct {
	ID           string
	Status       string
	ResolvedAt   *time.Time
	RejectReason *string
}

func (q *Queries) ResolveProposal(ctx context.Context, arg ResolveProposalParams) error {
	_, err := q.db.Exec(ctx, resolveProposal,
		arg.ID,
		arg.Status,
		arg.ResolvedAt,
		arg.RejectReason,
	)
	return err
}
