// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlcgen

import (
	"context"
	"time"
)

const activeLocalDates = `-- name: ActiveLocalDates :many
SELECT s.local_on FROM session s WHERE s.goal_id = $1 AND s.local_on > current_date - $2::int
UNION
SELECT e.local_on FROM evidence e WHERE e.goal_id = $1 AND e.local_on > current_date - $2::int
`

type ActiveLocalDatesParams struct {
	GoalID  string
	Column2 int32
}

func (q *Queries) ActiveLocalDates(ctx context.Context, arg ActiveLocalDatesParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, activeLocalDates, arg.GoalID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var local_on time.Time
		if err := rows.Scan(&local_on); err != nil {
			return nil, err
		}
		items = append(items, local_on)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO session (id, goal_id, user_id, action_id, started_at, duration_min, note, energy, local_on, created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type InsertSessionParams struct {
	ID          string
	GoalID      string
	UserID      string
	ActionID    *string
	StartedAt   time.Time
	DurationMin int16
	Note        *string
	Energy      *int16
	LocalOn     time.Time
	CreatedAt   time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.GoalID,
		arg.UserID,
		arg.ActionID,
		arg.StartedAt,
		arg.DurationMin,
		arg.Note,
		arg.Energy,
		arg.LocalOn,
		arg.CreatedAt,
	)
	return err
}

const listSessionsByGoal = `-- name: ListSessionsByGoal :many
SELECT id, goal_id, user_id, action_id, started_at, duration_min, note, energy, local_on, created_at
FROM session WHERE goal_id = $1 ORDER BY started_at DESC LIMIT $2
`

type ListSessionsByGoalParams struct {
	GoalID string
	Limit  int32
}

func (q *Queries) ListSessionsByGoal(ctx context.Context, arg ListSessionsByGoalParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByGoal, arg.GoalID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.ActionID,
			&i.StartedAt,
			&i.DurationMin,
			&i.Note,
			&i.Energy,
			&i.LocalOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumSessionMinutes = `-- name: SumSessionMinutes :one
SELECT coalesce(sum(duration_min), 0)::int AS total FROM session WHERE goal_id = $1
`

func (q *Queries) SumSessionMinutes(ctx context.Context, goalID string) (int32, error) {
	row := q.db.QueryRow(ctx, sumSessionMinutes, goalID)
	var total int32
	err := row.Scan(&total)
	return total, err
}
