// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: track.sql

package sqlcgen

import (
	"context"
	"time"
)

const getCurrentTrack = `-- name: GetCurrentTrack :one
SELECT id, goal_id, user_id, version, generated_by, accepted_at, superseded_at
FROM track WHERE goal_id = $1 AND superseded_at IS NULL
ORDER BY version DESC LIMIT 1
`

type GetCurrentTrackRow struct {
	ID           string
	GoalID       string
	UserID       string
	Version      int32
	GeneratedBy  string
	AcceptedAt   *time.Time
	SupersededAt *time.Time
}

func (q *Queries) GetCurrentTrack(ctx context.Context, goalID string) (GetCurrentTrackRow, error) {
	row := q.db.QueryRow(ctx, getCurrentTrack, goalID)
	var i GetCurrentTrackRow
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.Version,
		&i.GeneratedBy,
		&i.AcceptedAt,
		&i.SupersededAt,
	)
	return i, err
}

const getMilestone = `-- name: GetMilestone :one
SELECT id, track_id, goal_id, user_id, ordinal, title, completion_criteria, status, completed_at
FROM milestone WHERE id = $1 AND user_id = $2
`

type GetMilestoneParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetMilestone(ctx context.Context, arg GetMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, getMilestone, arg.ID, arg.UserID)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.GoalID,
		&i.UserID,
		&i.Ordinal,
		&i.Title,
		&i.CompletionCriteria,
		&i.Status,
		&i.CompletedAt,
	)
	return i, err
}

const insertMilestone = `-- name: InsertMilestone :exec
INSERT INTO milestone (id, track_id, goal_id, user_id, ordinal, title, completion_criteria, status, completed_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertMilestoneParams struct {
	ID                 string
	TrackID            string
	GoalID             string
	UserID             string
	Ordinal            int32
	Title              string
	CompletionCriteria string
	Status             string
	CompletedAt        *time.Time
}

func (q *Queries) InsertMilestone(ctx context.Context, arg InsertMilestoneParams) error {
	_, err := q.db.Exec(ctx, insertMilestone,
		arg.ID,
		arg.TrackID,
		arg.GoalID,
		arg.UserID,
		arg.Ordinal,
		arg.Title,
		arg.CompletionCriteria,
		arg.Status,
		arg.CompletedAt,
	)
	return err
}

const insertMilestoneCompetency = `-- name: InsertMilestoneCompetency :exec
INSERT INTO milestone_competency (milestone_id, competency_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertMilestoneCompetencyParams struct {
	MilestoneID  string
	CompetencyID string
}

func (q *Queries) InsertMilestoneCompetency(ctx context.Context, arg InsertMilestoneCompetencyParams) error {
	_, err := q.db.Exec(ctx, insertMilestoneCompetency, arg.MilestoneID, arg.CompetencyID)
	return err
}

const insertTrack = `-- name: InsertTrack :exec
INSERT INTO track (id, goal_id, user_id, version, generated_by, accepted_at, superseded_at)
VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type InsertTrackParams struct {
	ID           string
	GoalID       string
	UserID       string
	Version      int32
	GeneratedBy  string
	AcceptedAt   *time.Time
	SupersededAt *time.Time
}

func (q *Queries) InsertTrack(ctx context.Context, arg InsertTrackParams) error {
	_, err := q.db.Exec(ctx, insertTrack,
		arg.ID,
		arg.GoalID,
		arg.UserID,
		arg.Version,
		arg.GeneratedBy,
		arg.AcceptedAt,
		arg.SupersededAt,
	)
	return err
}

const listMilestoneCompetenciesByMilestones = `-- name: ListMilestoneCompetenciesByMilestones :many
SELECT milestone_id, competency_id FROM milestone_competency
WHERE milestone_id = ANY($1::uuid[])
`

func (q *Queries) ListMilestoneCompetenciesByMilestones(ctx context.Context, dollar_1 []string) ([]MilestoneCompetency, error) {
	rows, err := q.db.Query(ctx, listMilestoneCompetenciesByMilestones, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MilestoneCompetency
	for rows.Next() {
		var i MilestoneCompetency
		if err := rows.Scan(&i.MilestoneID, &i.CompetencyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestonesByTrack = `-- name: ListMilestonesByTrack :many
SELECT id, track_id, goal_id, user_id, ordinal, title, completion_criteria, status, completed_at
FROM milestone WHERE track_id = $1 ORDER BY ordinal
`

func (q *Queries) ListMilestonesByTrack(ctx context.Context, trackID string) ([]Milestone, error) {
	rows, err := q.db.Query(ctx, listMilestonesByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Milestone
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.GoalID,
			&i.UserID,
			&i.Ordinal,
			&i.Title,
			&i.CompletionCriteria,
			&i.Status,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeTrack = `-- name: SupersedeTrack :exec
UPDATE track SET superseded_at = now() WHERE id = $1
`

func (q *Queries) SupersedeTrack(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, supersedeTrack, id)
	return err
}

const updateMilestone = `-- name: UpdateMilestone :exec
UPDATE milestone SET status = $2, completed_at = $3 WHERE id = $1
`

type UpdateMilestoneParams struct {
	ID          string
	Status      string
	CompletedAt *time.Time
}

func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) error {
	_, err := q.db.Exec(ctx, updateMilestone, arg.ID, arg.Status, arg.CompletedAt)
	return err
}
