/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica e cria sessão */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** Format: password */
                        password: string;
                        /** @enum {string} */
                        client: "web" | "mobile";
                    };
                };
            };
            responses: {
                /**
                 * @description `web` recebe cookie HttpOnly e `token` nulo.
                 *     `mobile` recebe o token no corpo, para guardar no SecureStore.
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                            token?: string | null;
                            /** Format: date-time */
                            expiresAt?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoga a sessão atual */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description sessão revogada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário e preferências */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza fuso e janela de silêncio */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example America/Sao_Paulo */
                        timezone?: string;
                        quietHoursFrom?: number;
                        quietHoursTo?: number;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tudo que a tela inicial precisa, em uma chamada
         * @description Retorna no máximo 3 metas ativas (RN-02), cada uma com sua única ação
         *     pendente (RN-03), mais o nudge do dia se houver (RN-08).
         *     Uma chamada só, de propósito: o mobile abre nesta tela.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            goals: components["schemas"]["TodayGoal"][];
                            nudge?: components["schemas"]["Nudge"] | null;
                            consistency: components["schemas"]["Consistency"];
                            pendingProposals?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["GoalStatus"][];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GoalSummary"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Cria meta em rascunho
         * @description Só o essencial. A definição de pronto e as competências podem vir depois,
         *     pela sondagem — a fricção na criação é o que mata o entusiasmo (D2).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                        archetype: components["schemas"]["GoalArchetype"];
                        /**
                         * @example golang
                         * @example english
                         */
                        packId: string;
                        why?: string;
                    };
                };
            };
            responses: {
                /** @description rascunho criado, com a sondagem já aberta */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            goal?: components["schemas"]["Goal"];
                            probe?: components["schemas"]["Probe"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Goal"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        why?: string;
                        definitionOfDone?: string;
                        /** Format: date */
                        horizonOn?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Goal"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/goals/{goalId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ativa a meta (RN-01, RN-02)
         * @description Falha com `409` se faltar definição de pronto ou 3 competências (RN-01),
         *     ou se já houver 3 metas ativas (RN-02). No segundo caso o corpo do erro
         *     traz `activeGoals`, para a UI perguntar qual pausar em vez de só reclamar.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description pausa esta meta na mesma transação, liberando o slot
                         */
                        pauseGoalId?: string;
                    };
                };
            };
            responses: {
                /** @description ativada, já com a primeira ação gerada (RN-03) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            goal?: components["schemas"]["Goal"];
                            action?: components["schemas"]["NextAction"];
                        };
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pausa consciente — não é fracasso (§10) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        reviewOn: string;
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Goal"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/scope": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reduz ou restaura o escopo (§7.6) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        mode: "normal" | "minimal";
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            goal?: components["schemas"]["Goal"];
                            action?: components["schemas"]["NextAction"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conclui ou encerra a meta — exige debrief (RN-10)
         * @description O debrief vem no mesmo comando de propósito. É a única fricção obrigatória
         *     do sistema, e ela existe porque é onde está o aprendizado — inclusive,
         *     e principalmente, quando você está largando.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        outcome: "completed" | "abandoned";
                        debrief: components["schemas"]["DebriefInput"];
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Goal"];
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        /** Estado da sondagem e a pergunta atual */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Probe"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/probe/answer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Responde e recebe a próxima pergunta (ou o fim)
         * @description Adaptativa: cada resposta poda a árvore. Teto de 5 perguntas, garantido
         *     no banco. `nextQuestion` nulo significa que a sondagem se encerrou.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        turnId: string;
                        answer: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            probe?: components["schemas"]["Probe"];
                            nextQuestion?: components["schemas"]["ProbeTurn"] | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/probe/skip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pular — sempre disponível, sem penalidade
         * @description Competências não sondadas ficam com `level: null` (desconhecido),
         *     nunca `0`. A diferença importa: zero é uma afirmação, null é a ausência dela.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Probe"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/delta": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        /**
         * Painel de Delta (§7.1) — a tela principal de uma meta
         * @description Não mostra "quanto falta". Mostra o quanto você andou, por competência,
         *     contra o seu próprio baseline (P2). Competências aposentadas ficam fora.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeltaPanel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/competencies/{competencyId}/history": {
        parameters: {
            query?: {
                since?: string;
            };
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
                competencyId: components["parameters"]["CompetencyId"];
            };
            cookie?: never;
        };
        /** Série temporal de níveis — o gráfico de evolução */
        get: {
            parameters: {
                query?: {
                    since?: string;
                };
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                    competencyId: components["parameters"]["CompetencyId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LevelEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/competencies/{competencyId}/level": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
                competencyId: components["parameters"]["CompetencyId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Define o nível você mesmo (RN-04, via aceite explícito) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                    competencyId: components["parameters"]["CompetencyId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        level: number;
                        rationale: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Competency"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/projection": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        /**
         * Projeção honesta (§7.2)
         * @description Só existe com pelo menos 3 semanas de histórico. Sem isso, `available:false`
         *     e a UI diz que ainda está medindo — em vez de inventar uma previsão bonita.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Projection"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/consistency": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        /** Dias ativos em janela móvel de 30 dias (RN-11) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Consistency"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        /** Snapshots semanais com o relato do Coach */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Snapshot"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/track": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        /** Trilha vigente, com o que já ficou para trás */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
            };
        };
        put?: never;
        /** Pede uma revisão de trilha ao Planejador */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description revisão enfileirada; chega como proposta (RN-07) */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobAccepted"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/action": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        /** A única ação pendente da meta (RN-03) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NextAction"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Cria uma ação sua, substituindo a atual
         * @description O sistema nunca fica travado por causa da IA — você pode escrever a sua.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                        detail?: string;
                        estimatedMin?: number;
                        /** Format: uuid */
                        competencyId?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NextAction"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{actionId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actionId: components["parameters"]["ActionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conclui a ação e já devolve a próxima (RN-03)
         * @description A próxima ação vem na mesma resposta. Nunca existe um instante em que
         *     você olha a tela e não sabe o que fazer — é onde a meta morre (Problema C).
         *     Se o agente falhar, vem uma ação de fallback do pack.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    actionId: components["parameters"]["ActionId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default false */
                        usedMinimalVariant?: boolean;
                        durationMin?: number;
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            completed?: components["schemas"]["NextAction"];
                            next?: components["schemas"]["NextAction"];
                            session?: components["schemas"]["Session"] | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{actionId}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actionId: components["parameters"]["ActionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pula a ação — o motivo alimenta a calibragem (§7.3) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    actionId: components["parameters"]["ActionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: components["schemas"]["SkipReason"];
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description próxima ação já calibrada pelo motivo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            next?: components["schemas"]["NextAction"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    cursor?: components["parameters"]["Cursor"];
                };
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Page"] & {
                            items?: components["schemas"]["Session"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Registra sessão — insumo, não progresso (P1) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date-time */
                        startedAt: string;
                        durationMin: number;
                        note?: string;
                        energy?: number;
                        /** Format: uuid */
                        actionId?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sobe um arquivo (áudio de inglês, anexo) e devolve a chave */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            blobKey?: string;
                            sizeBytes?: number;
                        };
                    };
                };
                413: components["responses"]["PayloadTooLarge"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        /**
         * Museu de evidências (§7.4)
         * @description Ordem crescente por padrão — o museu é feito para comparar o antigo com o
         *     novo, e ver o começo primeiro é o que produz a sensação de distância percorrida.
         */
        get: {
            parameters: {
                query?: {
                    competencyId?: string;
                    order?: "asc" | "desc";
                    limit?: components["parameters"]["Limit"];
                    cursor?: components["parameters"]["Cursor"];
                };
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Page"] & {
                            items?: components["schemas"]["EvidenceCard"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Submete evidência — a moeda real do sistema (P1)
         * @description Responde `202` imediatamente. A avaliação é assíncrona porque leva de 5 a 30s
         *     e não pode ficar no caminho crítico de um request. O cliente acompanha por
         *     `GET /evidence/{id}/assessment`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        kind: components["schemas"]["EvidenceKind"];
                        title?: string;
                        body?: string;
                        blobKey?: string;
                        /** Format: uri */
                        externalUrl?: string;
                        language?: string;
                        /** Format: uuid */
                        actionId?: string;
                        /**
                         * Format: uuid
                         * @description correção cria nova evidência; a antiga é imutável (RN-06)
                         */
                        supersedesId?: string;
                    };
                };
            };
            responses: {
                /** @description evidência gravada, avaliação enfileirada */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            evidence?: components["schemas"]["Evidence"];
                            job?: components["schemas"]["JobAccepted"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{evidenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    evidenceId: components["parameters"]["EvidenceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Evidence"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{evidenceId}/assessment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        /**
         * Resultado da avaliação
         * @description `202` enquanto o job roda — não existe avaliação "pendente" gravada no banco
         *     (§18.4 do modelo de dados). `200` quando pronta, com `status: failed` se o
         *     agente não conseguiu, porque "não consegui avaliar isso" é informação legítima.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    evidenceId: components["parameters"]["EvidenceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description pronta */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Assessment"];
                    };
                };
                /** @description ainda avaliando */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobAccepted"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: "pending" | "accepted" | "rejected" | "expired";
                    goalId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{proposalId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aceita — só aqui a proposta vira estado (RN-07) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    proposalId: components["parameters"]["ProposalId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description ajustes seus antes de aplicar. O agente propõe, você decide (P8). */
                        edits?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description aplicada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{proposalId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    proposalId: components["parameters"]["ProposalId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Proposal"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{goalId}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        /** Recursos curados — só os com link verificado */
        get: {
            parameters: {
                query?: {
                    competencyId?: string;
                };
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"][];
                    };
                };
            };
        };
        put?: never;
        /** Pede curadoria ao A4 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    goalId: components["parameters"]["GoalId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        competencyId?: string;
                        /** @description ex: "não entendi errgroup" */
                        gap?: string;
                    };
                };
            };
            responses: {
                /** @description busca enfileirada; links são verificados por HTTP antes de aparecer */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobAccepted"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{resourceId}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    resourceId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        consumed?: boolean;
                        rating?: number;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nudges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Nudge"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nudges/{nudgeId}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nudgeId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Marca visualização ou ação
         * @description Alimenta a métrica de eficácia do Coach. Um nudge que nunca é aberto é um
         *     nudge que precisa mudar de tom, não de frequência.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    nudgeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        event: "opened" | "acted" | "dismissed";
                    };
                };
            };
            responses: {
                /** @description ok */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra o token de push do Expo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        expoToken: string;
                        /** @enum {string} */
                        platform: "android" | "ios" | "web";
                    };
                };
            };
            responses: {
                /** @description ok */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "ok" | "degraded";
                            db?: boolean;
                            queue?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gasto do mês e tier vigente (§6.3 da arquitetura) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date */
                            periodOn?: string;
                            limitUsd?: number;
                            spentUsd?: number;
                            /** @description true quando strong foi rebaixado */
                            degraded?: boolean;
                            callsThisMonth?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        GoalArchetype: "skill" | "habit" | "project" | "metric";
        /** @enum {string} */
        GoalStatus: "draft" | "active" | "at_risk" | "stagnant" | "paused" | "completed" | "abandoned";
        /**
         * @description `unknown` = nunca medido. `low` = auto-declarado na sondagem ou nível
         *     vencido por desuso. `medium` = uma avaliação. `high` = consolidado.
         * @enum {string}
         */
        Confidence: "unknown" | "low" | "medium" | "high";
        /** @enum {string} */
        SkipReason: "too_hard" | "too_easy" | "no_time" | "not_relevant" | "other";
        /** @enum {string} */
        EvidenceKind: "code_snippet" | "repo_link" | "commit_diff" | "exercise_solution" | "written_text" | "audio_recording" | "listening_log" | "shadowing_clip" | "file";
        /** @enum {string} */
        NudgeKind: "recognition" | "recovery" | "recalibration" | "scope_reduction" | "revision";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            timezone: string;
            quietHoursFrom?: number | null;
            quietHoursTo?: number | null;
        };
        Page: {
            nextCursor?: string | null;
            hasMore?: boolean;
        };
        JobAccepted: {
            jobId: string;
            /** @enum {string} */
            state: "queued" | "running" | "failed";
            /** @description dica de polling para o cliente */
            retryAfterMs?: number;
        };
        GoalSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            archetype: components["schemas"]["GoalArchetype"];
            packId: string;
            status: components["schemas"]["GoalStatus"];
            /** @enum {string} */
            scopeMode?: "normal" | "minimal";
            daysActive?: number;
            /** Format: date-time */
            lastActivityAt?: string | null;
        };
        Goal: components["schemas"]["GoalSummary"] & {
            why?: string | null;
            definitionOfDone?: string | null;
            /** Format: date */
            horizonOn?: string | null;
            /** Format: date */
            pausedUntil?: string | null;
            competencies?: components["schemas"]["Competency"][];
            /** @description RN-01 satisfeita */
            readyToActivate?: boolean;
            /** @description o que falta para ativar, em linguagem humana */
            blockers?: string[];
        };
        TodayGoal: {
            goal: components["schemas"]["GoalSummary"];
            action: components["schemas"]["NextAction"];
            /**
             * @description Uma linha sobre algo que subiu recentemente. Aparece na tela inicial
             *     porque o produto existe para tornar evolução visível, não para cobrar.
             */
            recentWin?: string | null;
        };
        DebriefInput: {
            whatWorked: string;
            whatDidnt: string;
            whatSurvives?: string;
            wouldRetry?: boolean;
        };
        Probe: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "open" | "completed" | "skipped";
            askedCount: number;
            /**
             * @description Teto garantido no banco. Um agente entusiasmado não consegue
             *     transformar a sondagem num questionário nem que queira (D2).
             * @constant
             */
            maxQuestions: 5;
            currentQuestion?: components["schemas"]["ProbeTurn"] | null;
            turns?: components["schemas"]["ProbeTurn"][];
            /**
             * @description sempre verdadeiro. O botão de "começar agora" nunca some.
             * @constant
             */
            canSkip?: true;
        };
        ProbeTurn: {
            /** Format: uuid */
            id: string;
            ordinal: number;
            question: string;
            answer?: string | null;
            /** Format: uuid */
            competencyId?: string | null;
            inferredLevel?: number | null;
            /** Format: date-time */
            answeredAt?: string | null;
        };
        Competency: {
            /** Format: uuid */
            id: string;
            packKey: string;
            label: string;
            weight: number;
            /** @description `null` = desconhecido, que é diferente de `0` = não iniciado */
            level?: number | null;
            /** @description o texto do pack para este nível. A UI mostra isto, não o número. */
            levelDescriptor?: string | null;
            baselineLevel?: number | null;
            confidence: components["schemas"]["Confidence"];
            /** Format: date-time */
            lastEvidenceAt?: string | null;
            /** @description dias sem evidência; alimenta o aviso de "não verificado" (RN-05) */
            staleDays?: number | null;
            /** @default false */
            retired: boolean;
        };
        DeltaPanel: {
            /** Format: uuid */
            goalId: string;
            daysActive: number;
            competencies: (components["schemas"]["Competency"] & {
                /** @description nível atual menos baseline. O número que importa. */
                delta?: number | null;
                deltaWindowDays?: number | null;
                risesLast90d?: number;
            })[];
            totals: {
                evidenceCount?: number;
                milestonesDone?: number;
                sessionMinutes?: number;
            };
            /**
             * @description Uma frase comparando você com o seu eu passado (P2), ex.:
             *     "Há 60 dias você não usava context.Context; hoje aparece em 3 evidências."
             */
            headline?: string | null;
        };
        LevelEvent: {
            /** Format: uuid */
            id: string;
            fromLevel?: number | null;
            toLevel: number;
            confidence?: components["schemas"]["Confidence"];
            /** @enum {string} */
            source: "probe" | "self" | "assessment" | "weekly_consolidation" | "decay" | "revalidation";
            /**
             * @description Obrigatório. Nível que muda sem explicação é nível em que você não
             *     confia, e um número em que você não confia não motiva ninguém.
             */
            rationale: string;
            /** Format: uuid */
            assessmentId?: string | null;
            /** Format: date-time */
            occurredAt: string;
        };
        Projection: {
            available: boolean;
            /** @description quando indisponível, ex. "ainda coletando ritmo (2 de 3 semanas)" */
            reason?: string | null;
            minutesPerWeek?: number | null;
            nextMilestone?: string | null;
            weeksToNextMin?: number | null;
            weeksToNextMax?: number | null;
            /** @description cenário alternativo, sempre em intervalo — nunca número seco */
            ifYouDouble?: string | null;
        };
        Consistency: {
            activeDays: number;
            /** @default 30 */
            windowDays: number;
            todayDone?: boolean;
            /**
             * @description Ex.: "18 dos últimos 30 dias". Nunca uma streak que zera (RN-11, P6) —
             *     nenhum campo desta API expõe contador consecutivo, de propósito.
             */
            label?: string;
        };
        Snapshot: {
            /** Format: date */
            periodOn?: string;
            levels?: {
                [key: string]: number;
            };
            deltas?: {
                [key: string]: number;
            };
            milestonesDone?: number;
            evidenceCount?: number;
            sessionMinutes?: number;
            activeDays?: number;
            narrative?: string | null;
        };
        Track: {
            /** Format: uuid */
            id?: string;
            version?: number;
            milestones?: components["schemas"]["Milestone"][];
        };
        Milestone: {
            /** Format: uuid */
            id: string;
            ordinal: number;
            title: string;
            completionCriteria?: string;
            /** @enum {string} */
            status: "locked" | "current" | "completed" | "skipped";
            /** Format: date-time */
            completedAt?: string | null;
            competencyIds?: string[];
        };
        NextAction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            goalId: string;
            title: string;
            detail?: string | null;
            practiceFormat?: string | null;
            /** @description teto de 30 min garantido no banco (P4) */
            estimatedMin: number;
            /** @description a versão de 5 minutos. Cumprir o mínimo conta como dia ativo (§7.5). */
            minimalVariant?: string | null;
            /** Format: uuid */
            competencyId?: string | null;
            /** Format: uuid */
            milestoneId?: string | null;
            /** @enum {string} */
            generatedBy?: "agent" | "user" | "fallback";
            /** @enum {string|null} */
            originKind?: "practice" | "revalidation" | "recovery" | null;
            /** @enum {string} */
            status: "pending" | "completed" | "skipped";
            /** Format: date-time */
            createdAt?: string;
        };
        Session: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            startedAt?: string;
            durationMin?: number;
            /** Format: date */
            localOn?: string;
            note?: string | null;
            energy?: number | null;
        };
        Evidence: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["EvidenceKind"];
            title?: string | null;
            body?: string | null;
            /** @description URL assinada e temporária */
            blobUrl?: string | null;
            externalUrl?: string | null;
            language?: string | null;
            /** Format: uuid */
            supersedesId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        EvidenceCard: components["schemas"]["Evidence"] & {
            competencyIds?: string[];
            assessmentSummary?: string | null;
            /**
             * @description Nível de cada competência **no momento desta evidência**, reconstruído
             *     a partir de `competency_level_event` (consulta point-in-time). É o que
             *     permite o museu mostrar "você aqui" ao lado de "você hoje".
             */
            levelsAtTime?: {
                [key: string]: number;
            };
        };
        Assessment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            evidenceId: string;
            /** @enum {string} */
            kind: "daily" | "weekly_consolidation" | "self";
            /** @enum {string} */
            status: "ready" | "failed";
            summary?: string | null;
            strengths?: string[];
            gaps?: {
                /** Format: uuid */
                competencyId?: string | null;
                issue?: string;
                /** @description ex: "linha 14" */
                where?: string | null;
                howToFix?: string | null;
            }[];
            scores?: {
                /** Format: uuid */
                competencyId?: string;
                proposedLevel?: number;
                /**
                 * @description O que na SUA evidência sustenta a nota. Obrigatório — é o que
                 *     separa "melhore seu tratamento de erros" de algo acionável.
                 */
                observed?: string;
                /** @description false até a consolidação semanal confirmar (RN-04) */
                consolidated?: boolean;
            }[];
            /** Format: date-time */
            createdAt?: string;
        };
        Proposal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            goalId?: string | null;
            /** @enum {string} */
            kind: "track" | "milestone_revision" | "level_change" | "scope_reduction" | "pack_draft" | "competency_set";
            payload?: {
                [key: string]: unknown;
            };
            rationale: string;
            /** @enum {string} */
            status: "pending" | "accepted" | "rejected" | "expired";
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        Resource: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
            title: string;
            /** @enum {string|null} */
            kind?: "article" | "video" | "repo" | "exercise" | "podcast" | "doc" | "book" | null;
            /** @description por que ESTE recurso, para VOCÊ, AGORA — não uma lista genérica */
            whyNow: string;
            estimatedMin?: number | null;
            /**
             * Format: date-time
             * @description Sempre preenchido. Recurso sem verificação HTTP não é exposto — link
             *     inventado destrói a confiança no sistema inteiro.
             */
            verifiedAt?: string;
            /** Format: date-time */
            consumedAt?: string | null;
            rating?: number | null;
        };
        Nudge: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            goalId?: string | null;
            kind: components["schemas"]["NudgeKind"];
            title: string;
            body: string;
            actionLabel?: string | null;
            actionRoute?: string | null;
            /** Format: date-time */
            deliveredAt?: string | null;
        };
        /** @description RFC 9457 */
        Problem: {
            /** @example https://lifeos/errors/max-active-goals */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** @description a regra de negócio violada, ex: "RN-02" */
            rule?: string | null;
            errors?: {
                field?: string;
                message?: string;
            }[];
            /** @description presente no erro de RN-02, para a UI perguntar qual pausar */
            activeGoals?: components["schemas"]["GoalSummary"][];
        };
    };
    responses: {
        /** @description não autenticado */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description não encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description conflito com uma regra de negócio */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description payload válido mas incompleto para a operação */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description rate limit */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description arquivo grande demais */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        GoalId: string;
        CompetencyId: string;
        ActionId: string;
        EvidenceId: string;
        ProposalId: string;
        Limit: number;
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
